name: Run Batch Scripts

on:
  push:
    paths:
      - 'script/**'
      - 'upload/**'
      - '.github/workflows/run-bats.yml'
  workflow_dispatch:

jobs:
  run-bat:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Jalankan depencies.bat
        run: script\depencies.bat

      - name: Jalankan checker.bat
        run: script\checker.bat
