name: AeNux Render Workflow

on:
  workflow_dispatch:
    inputs:
      compName:
        description: "Composition Name"
        required: true
        default: "MainComp"
      outputName:
        description: "Output video Name"
        required: true
        default: "output"

jobs:
  render:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Jalankan depencies.bat
        run: script\depencies.bat

      - name: Temukan file ZIP pertama di folder upload
        id: zipfile
        run: |
          $zip = Get-ChildItem -Path "upload" -Filter *.zip | Select-Object -First 1
          if (-not $zip) { throw "Tidak ada file .zip di folder upload" }
          echo "zipPath=$($zip.FullName)" >> $env:GITHUB_OUTPUT

      - name: Ekstrak ZIP ke folder inputProject
        run: |
          $target = "inputProject"
          if (Test-Path $target) { Remove-Item -Recurse -Force $target }
          New-Item -ItemType Directory -Path $target | Out-Null
          Expand-Archive -Path "${{ steps.zipfile.outputs.zipPath }}" -DestinationPath $target -Force

      - name: Jalankan aerender (output .mp4)
        run: |
          $target = "inputProject"
          $compName = "${{ github.event.inputs.compName }}"
          $outputNameRaw = "${{ github.event.inputs.outputName }}"

          # Pastikan output berakhiran .mp4 (hindari double extension)
          if ($outputNameRaw -notlike "*.mp4") {
            $outputName = "$outputNameRaw.mp4"
          } else {
            $outputName = $outputNameRaw
          }

          # Cari file .aep
          $aepFile = Get-ChildItem -Path $target -Filter *.aep | Select-Object -First 1
          if (-not $aepFile) { throw "File .aep tidak ditemukan di folder $target" }

          Write-Host "Render file:" $aepFile.FullName
          Write-Host "Composition:" $compName
          Write-Host "Output file:" "${{ github.workspace }}\$outputName"

          & "C:\Program Files\Adobe\Adobe After Effects 2024\Support Files\aerender.exe" `
            -project $aepFile.FullName `
            -comp $compName `
            -output "${{ github.workspace }}\$outputName"

      - name: Upload hasil render
        uses: actions/upload-artifact@v4
        with:
          name: render-output
          path: ${{ github.workspace }}\*.mp4
